apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      containers:
        - name: go-hello-world
          image: ytimocinacr.azurecr.io/ytimocin/go-hello-world
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-world-service
spec:
  selector:
    app: go-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
